import ImageGallery from "../components/imageGallery/ImageGallery";

const permanent = [
  "/gallery/permanent/001.jpg",
  "/gallery/permanent/01.jpg",
  "/gallery/permanent/02.jpg",
  "/gallery/permanent/03.jpg",
  "/gallery/permanent/04.jpg",
  "/gallery/permanent/05.jpg",
  "/gallery/permanent/06.jpg",
  "/gallery/permanent/07.jpg",
  "/gallery/permanent/08.jpg",
  "/gallery/permanent/09.jpg",
  "/gallery/permanent/10.jpg",
  "/gallery/permanent/11.jpg",
  "/gallery/permanent/12.jpg",
  "/gallery/permanent/13.jpg",
  "/gallery/permanent/14.jpg",
  "/gallery/permanent/15.jpg",
  "/gallery/permanent/16.jpg",
  "/gallery/permanent/17.jpg",
  "/gallery/permanent/18.jpg",
  "/gallery/permanent/19.jpg",
  "/gallery/permanent/20.jpg",
  "/gallery/permanent/21.jpg",
  "/gallery/permanent/21.jpg",
  "/gallery/permanent/22.jpg",
  "/gallery/permanent/23.jpg",
  "/gallery/permanent/24.jpg",
  "/gallery/permanent/25.jpg",
  "/gallery/permanent/26.jpg",
  "/gallery/permanent/27.jpg",
  "/gallery/permanent/28.jpg",
  "/gallery/permanent/29.jpg",
  "/gallery/permanent/30.jpg",
  "/gallery/permanent/31.jpg",
  "/gallery/permanent/32.jpg",
  "/gallery/permanent/c_1.jpg",
  "/gallery/permanent/c_2.jpg",
  "/gallery/permanent/c_3.jpg",
  "/gallery/permanent/greenhouse.jpg",
  "/gallery/permanent/n_4.jpg",
  "/gallery/permanent/n_5.jpg"
];

const eventDomes = [
  "/gallery/event_domes/00.jpg",
  "/gallery/event_domes/01.jpg",
  "/gallery/event_domes/02.jpg",
  "/gallery/event_domes/03.jpg",
  "/gallery/event_domes/04.jpg",
  "/gallery/event_domes/05.jpg",
  "/gallery/event_domes/06.jpg",
  "/gallery/event_domes/07.jpg",
  "/gallery/event_domes/08.jpg",
  "/gallery/event_domes/09.jpg",
  "/gallery/event_domes/10.jpg",
  "/gallery/event_domes/11.jpg",
  "/gallery/event_domes/12.jpg",
  "/gallery/event_domes/13.jpg",
  "/gallery/event_domes/14.jpg",
  "/gallery/event_domes/15.jpg",
  "/gallery/event_domes/16.jpg",
  "/gallery/event_domes/17.jpg",
  "/gallery/event_domes/18.jpg",
  "/gallery/event_domes/19.jpg",
  "/gallery/event_domes/20.jpg",
  "/gallery/event_domes/21.jpg",
  "/gallery/event_domes/21.jpg",
  "/gallery/event_domes/22.jpg",
  "/gallery/event_domes/23.jpg",
  "/gallery/event_domes/24.jpg",
  "/gallery/event_domes/25.jpg",
  "/gallery/event_domes/26.jpg",
  "/gallery/event_domes/27.jpg",
  "/gallery/event_domes/28.jpg",
  "/gallery/event_domes/29.jpg",
  "/gallery/event_domes/30.jpg",
  "/gallery/event_domes/31.jpg",
  "/gallery/event_domes/32.jpg",
  "/gallery/event_domes/33.jpg",
  "/gallery/event_domes/34.jpg",
  "/gallery/event_domes/35.jpg",
  "/gallery/event_domes/36.jpg",
  "/gallery/event_domes/37.jpg",
  "/gallery/event_domes/38.jpg",
];

const concept = [
  "/gallery/concept/01.jpg",
  "/gallery/concept/02.jpg",
  "/gallery/concept/03.jpg",
  "/gallery/concept/04.jpg",
  "/gallery/concept/05.jpg",
  "/gallery/concept/06.jpg",
  "/gallery/concept/07.jpg",
  "/gallery/concept/08.jpg",
  "/gallery/concept/09.jpg",
  "/gallery/concept/10.jpg",
  "/gallery/concept/11.jpg",
  "/gallery/concept/12.jpg",
  "/gallery/concept/13.jpg",
  "/gallery/concept/14.jpg",
  "/gallery/concept/15.jpg",
  "/gallery/concept/16.jpg",
  "/gallery/concept/17.jpg",
  "/gallery/concept/18.jpg",
  "/gallery/concept/19.jpg",
  "/gallery/concept/20.jpg",
  "/gallery/concept/21.jpg",
  "/gallery/concept/21.jpg",
  "/gallery/concept/22.jpg",
  "/gallery/concept/23.jpg",
  "/gallery/concept/24.jpg",
  "/gallery/concept/25.jpg",
  "/gallery/concept/26.jpg"
];

const gallery = [
  { 
    label: "Permanent", 
    content: (<ImageGallery images={permanent} />)
  },
  { 
    label: "Event Domes", 
    content: (<ImageGallery images={eventDomes} />)
  },
  { 
    label: "Concept projects", 
    content: (<ImageGallery images={concept} />)
  }
];

export default gallery;
